################################
# Site Settings
################################
lang        : "en"
logo        :
title       : Minimal Theme
description : Your awesome site
author      : Joe Bloggs
email       : your-email@domain.com
baseurl     : "/minimal-jekyll-theme" # the subpath of your site, e.g. /blog
url         : "https://desiredpersona.github.io"
date_format : "%-d %b %Y"
port        : 5000


################################
# Theme Settings
################################
theme       : minimal-jekyll-theme
permalink   : /:title/

collections:
  docs:
    output: true
    permalink: /:collection/:path/

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

sass:
    sass_dir: _sass
    #style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Include/Exclude filetypes
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock


################################
# Analytics Settings
################################
google_analytics: UA-106595790-1
google_analytics_async: true # https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet
google_tag_manager:
facebook_pixel_id:


################################
# Jekyll Plugins
################################
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

# Jekyll SEO Tag Settings https://github.com/jekyll/jekyll-seo-tag
social:
  name: Joe Bloggs
  links:
    - https://twitter.com/username
    - https://plus.google.com/u/0/+username
    - https://www.facebook.com/username

twitter:
  username: JoeBloggs

facebook:
  app_id:
  publisher:
  admins:

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:

# Jekyll Feed Settings https://github.com/jekyll/jekyll-feed
atom_feed:
    path: # Leave blank to use default (feed.xml)

# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
     - categories
     - tags
     - year
     - month
     - day
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
